#39 Add support for PHP 8
gmponos/guzzle-log-middleware pull request #41
Opened 2021-07-01 12:39 UTC by joskfg

Allow PHP 8 versions

2021-08-11 09:53 UTC, BramG commented
Can someone commit this? It works as expected.

2021-08-12 08:09 UTC, vuphuong87 approved these changes

2021-08-12 08:11 UTC, vuphuong87 commented
Guess we can merge this one @gmponos ?
Thanks

2021-09-23 09:49 UTC, coccoinomane commented
The changes work for me too 👍
@gmponos would you mind accepting the pull request?

2021-09-25 08:49 UTC, kprovorov commented
Hi all! Any updates? :)

2021-10-06 15:04 UTC, GrahamCampbell requested changes

2021-10-06 15:04 UTC, GrahamCampbell commented on composer.json
> +        "php": "^7.2 || ^8",
`^7.2 || ^8.0` is the convention here

2021-11-12 12:42 UTC, merged

2021-11-12 12:42 UTC, gmponos commented
Thank you

2021-11-16 10:36 UTC, vuphuong87 commented
Could you release a new version for the recent merges? Thanks @gmponos

2022-02-28 17:19 UTC, kingeke commented
Hey @gmponos pls we're waiting for the new version, much thanks.